# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

#source: source
destination: _site
sass:
  sass_dir: _sass
  style: expanded # compressed # expanded

# permalink and highlighter
#permalink   : /:year/:title/
#markdown    : kramdown
#highlighter : rouge

# SEO settings
title: Verbis
description: "Improve your English vocabulary with Verbis."
keywords: "Verbis, Verbis android, android, application, English, vocabulary, Improve, words,verb"

# Site settings
url: http://verbis.in
baseurl: ""
# baseurl: ""

# Author settings
#author:
#  name      : Prashant Solanki
#  job       : Android Developer
#  bio       : "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee."
#  thumb     : /images/author.jpg
#  email     : nandomoreira.me@gmail.com
#  url       : http://nandomoreira.me
#  github    : http://github.com/nandomoreirame
#  twitter   : http://twitter.com/nandomoreirame
#  facebook  : http://facebook.com/fernando.dev
#  linkedin  : http://linkedin.com/in/nandomoreirame

# google_analytics: UA-52446115-1
repo: http://github.com/black-shift/verbis-landing

# comments
disqus_shortname: "fernandomoreira"
