# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

#source: source
destination: _site
sass:
  sass_dir: _sass
  style: expanded # compressed # expanded

# permalink and highlighter
#permalink   : /:year/:title/
#markdown    : kramdown
#highlighter : rouge

# SEO settings
title: Verbis
description: "Improve your English vocabulary with Verbis."
keywords: "Verbis, Verbis android, android, application, English, vocabulary, Improve, words,verb"

# Site settings
url: http://verbis.in
baseurl: ""
# baseurl: ""

# Author settings
#author:
#  name      : Prashant Solanki
#  job       : Android Developer
#  bio       : "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee."
#  thumb     : /images/author.jpg
#  email     : nandomoreira.me@gmail.com
#  url       : http://nandomoreira.me
#  github    : http://github.com/nandomoreirame
#  twitter   : http://twitter.com/nandomoreirame
#  facebook  : http://facebook.com/fernando.dev
#  linkedin  : http://linkedin.com/in/nandomoreirame

google-analytics: UA-77566313-1
repo: http://github.com/black-shift/verbis-landing
play-store-url: https://play.google.com/store/apps/details?id=com.blackshift.verbis
home-icon-url: https://lh3.googleusercontent.com/LZ52MTvpOU1OF3KcqdRg1Szuw-bULlEgTY4xo0GEKygFTy5vDkMIfeBNOIy3VNNuPWc=w300-rw
app-package-name: com.blackshift.verbis
google-client-id: 884193976507-ige922ag0kjqau32bte5gf3hqrbq7ssa.apps.googleusercontent.com

# comments
#disqus_shortname: "fernandomoreira"
